theme: jekyll-theme-slate

title: Tattoo Analysis
description: A compilation of tattoo analysis ressources
show_downloads: true 

github:
  repository_url: https://github.com/tattoo-analysis/tattoo_pigments_spectral_libraries
  zip_url: https://github.com/tattoo-analysis/tattoo_pigments_spectral_libraries/archive/master.zip
  owner_url: https://github.com/corinnabrungs
  owner_name: Corinna Brungs
